openapi: "3.0.0"
info:
  version: 1.0.0
  title: Jerens Web App
  description: TODO
  contact:
    name: Jerens Lensun
    url: https://www.jerenslensun.com/
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:

  /notification/subscribe:
    post:
      summary: Subscribe to notification
      operationId: subscribeNotification
      requestBody:
        description: Register new Token to a server
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscriber'
      responses:
        '201':
          description: todo
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /notification/status:
    post:
      summary: Subscriber Status
      operationId: subscriberStatus
      requestBody:
        description: Status of current subscriber
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscriber'
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /notification/send:
    post:
      summary: Send notification to all subscriber
      operationId: sendNotification
      requestBody:
        description: Register new Token to a server
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '200':
          description: todo
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Subscriber:
      required:
        - token
      properties:
        token:
          type: string
          description: Client Token
    Status:
      required:
        - status
      properties:
        status:
          type: boolean
          description: Subscriber status
    Message:
      required:
        - title
        - message
      properties:
        title:
          type: string
          description: Notification title
        message:
          type: string
          description: Notification message
    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string