name: Build and deploy a container to an Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened, closed]
      branches:
      - main

jobs:
  build:
    if: github.repository == 'jerensl/api.jerenslensun.com' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed'))
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t jerensl.azurecr.io/jerens-web-api:${{ github.sha }}
        docker push jerensl.azurecr.io/jerens-web-api:${{ github.sha }}   

  deploy:
    if: github.repository == 'jerensl/api.jerenslensun.com' && github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jerens-web-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'jerensl.azurecr.io/jerens-web-api:${{ github.sha }}'
